### ISSUE TITLE
WorkflowTask Status: When rerunning a workflow only partially, status of later tasks gets update late

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#1083] opened 2023-12-13 17:20 UTC
If I have run a full workflow, then just run the beginning (e.g. until Maximum Intensity Projection), then the status still shows done for Cellpose & Napari workflows wrapper while the workflow is running again:
<img width="1391" alt="Screenshot 2023-12-13 at 18 18 07" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/8882d0fa-b402-4d4b-a9cc-4d45f1f747c7">

And when it finishes, that status goes away.
<img width="1391" alt="Screenshot 2023-12-13 at 18 18 19" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/9ba72369-ad3d-4ec4-9bb9-af706f136283">

I would prefer it that it goes away immediately.

-----

On the other hand, when I then continue a workflow (e.g. run cellpose & napari workflows separately now), it correctly keeps showing the earlier statuses as done => as intended, that should stay this way!

**Comment by jluethi** [comment] 2024-04-11 15:08
+1 again on this issue, especially the "what happens to later steps of a workflow when rerun if an early step fails" => we should discuss how to handle that better

**Comment by tcompa** [comment] 2024-04-18 10:16
Context, how does the endpoint work at the moment:

1. It reads the status of each WorkflowTask from the Dataset history in the DB.
2. If a job is running, all the tasks involved are marked as "submitted"
3. If a job is running and there exist the temporary history file in its folder, then any workflowtask status listed there has the highest priority

To add:

4. If task with `order=N` in the task list is marked as failed, then all tasks with `order>N` must be removed from the response body.
5. If a job is running, and it goes up to task N, then all tasks with `order>N` must be removed from the response body.
6. If no job is running, and the last task that ran (either successfully or failed) has `order=N`, then all tasks with `order>N` must be removed from the response body. This extends the requirement 4 above, thus making it redundant.

> To review: Why is the behavior in 2 already the expected one after a job finishes?

We cannot reproduce this, and that's why point 6 above is still to do.

----

Note that this endpoint (both in the current version and after the proposed update) relies on the task list being fixed. If I add a task in the list, or if I reorder the list, it will most likely introduce inconsistent behaviors.
A mitigation for this issue is that within points 4-5-6, `order` should represent `current_task_list.index(wftask)` rather than `wftask.order`.


### Higher level

Even with this mitigation, there's room for many edge cases (TBD). I think we don't have tools, here, to track the status of a dynamically-changing task list in a consistent way. For the moment I simply suggest that we opt for not showing status for the workflow tasks where this information is ambiguous (this would anyway be part of a different issue/PR).

**Comment by tcompa** [comment] 2024-04-18 13:41
We explored this further with @mfranzon, and we do think that fully tackling this issue requires very different tools. The high-level comment is that we are lookging for a function that maps a very complex input (a dataset history, a dynamic workflow task list, possibly a running job, and a given workflow-task ID) into a very simple output (one of: submitted, done, failed, none), and it's very easy to find edge cases that do not fit in the current simplified structure. Some examples are listed in https://github.com/fractal-analytics-platform/fractal-server/issues/793#issuecomment-1648043804, but we can obviously come up with more scenarios as soon as the task list can change.

Trying to set priorities here, we are considering the following as **in scope**:

> We should provide a reasonable behavior (TBD) for when the task list was created by subsequently appending tasks to the existing list.

For the moment, we are considering the following as **not in scope**:

> We sould expose consistent information in case of
> 
> * I added a task in the middle of the task list
> * I removed a task
> * I changed the order of the existing task list

**Comment by jluethi** [comment] 2024-04-18 19:07
> For the moment, we are considering the following as not in scope:

Sounds like a good scope limit! Let's be aware of this as a larger review topic, but have the scope for 2.0 to have it work in the regular cases like rerunning (parts of) a workflow & rerunning from earlier tasks after task error.

**Closed** 2024-04-19 07:07 UTC
Labels: High Priority, History/Status, v2
