### ISSUE TITLE
In SLURM backend, set the slurm script and output/error to custom paths

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#284] opened 2022-11-18 07:30 UTC
I think that the `WORKFLOW_DIR` folder for a single-global-task workflow should look like:
```
0.args.json
0.err
0.out
0.metadiff.json
0.slurm.submit
0.slurm.err
0.slurm.out
```
this requires adding lines like:
```
#SBATCH --output=/SOME/PATH.out
#SBATCH --output=/SOME/PATH.err
```
in the sbatch file (defined here: https://github.com/sampsyo/clusterfutures/blob/master/cfut/slurm.py), and possibly also change the location of the submission script (in the ` submit_text` function).

**Comment by jacopo-exact** [comment] 2022-11-25 11:12
for parallel tasks, it is not possible to set custom per-component files unless we give up `Executor.map` altogether

**Comment by tcompa** [comment] 2022-11-25 11:23
Quick possible workaroun: can we create a folder with a simple name (`1.artifacts`) and plate out/err files in there, with arbitrary names?

**Comment by tcompa** [comment] 2022-11-25 11:53
Or, something else:
If these files go to some other arbitrary paths (the defaults are typically `jobid.err` and `jobid.out`, in **some** folder), but can we at least identify those two paths and write them into one of fractal logs?

**Comment by tcompa** [comment] 2022-11-25 11:55
Last fall-back option:
Is it "easy" to do it at least for serial tasks only? That would already be useful.

**Comment by jacopo-exact** [comment] 2022-11-25 11:56
serial tasks are almost trivial.
the problem is with parallel tasks, as the component is assigned to each slurm job only within the map function.

**Comment by tcompa** [comment] 2022-11-28 14:12
Quick update: it seems that now all files are in the correct folder, including the slurm submission/output files for parallel tasks. Great. Missing points:
- [ ] Conform to a standard filename (instead of things like `slurmpy.stdout.9410935.log` and `_temp_nJEN0ZYTWL4vhalvvkOKGwdTZaDk2cIf.sh`, I would expect `something.slurm.out`  and `something.slurm.sh`). This is not crucial, but would be nice.
- [ ] Also include the `--error` additional `SBATCH` line (in the same way as the `--output` one), pointing some `something.slurm.err`.

**Comment by jacopo-exact** [comment] 2022-11-28 14:13
working on it right now

**Closed** 2022-11-29 11:12 UTC
